<a href="https://colab.research.google.com/github/anshultaneja/DataScience/blob/main/Numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 0 - Topic 9
**Authors:** Sai Gayatri Vadali **|** Julián Darío Miranda.
# `Numpy`, Scientific and numeric library


`Numerical Python` popularly known as `Numpy` is core library for scientific computing. It provides high performance multi-dimensional array object and tools for working with these objects. 

In the following sections, we will be working on the `Numpy` library and its uses. We will compare the performance of some `Numpy` operations with their classic `Python` equivalent and discuss the uses of the library. Let us begin!

## 1. Comparing `Python` List vs `Numpy` array (This section is optional and can be skipped)

***You DON'T need to memorize this code - it is just to give you a comparison to know why NumPy is better. Reason: It could be overwhelming sometimes as a beginner so don't hesitate to simply skip section 1 and jump to section 2. However, please ensure you read the conclusion***

Consider the following snippet adapted from https://webcourses.ucf.edu/courses/. We start importing the `numpy` and `timeit` libraries. `Numpy`, as we have stated, enables scientific computing and high performance tasks executions with multi-dimensional or n-dimensional arrays. The `Timer` module from `timeit` library is used for the purpose of calculating the time that certain scripts take.

In [ ]:
import numpy as np
from timeit import Timer

With imported libraries, we proceed to create two example arrays with numbers in the range [0, 9999]:

In [ ]:
size_of_vec = 10000
X_list = range(size_of_vec)
Y_list = range(size_of_vec)
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)

To compare the performance of two scripts, one explicitly developed with `Python` and another with `Numpy`, we defined two user functions:

In [ ]:
def pure_python_version(): #Explicitly Python based with lists
    Z = []
    for i in range(len(X_list)):
        Z.append(X_list[i] + Y_list[i])
    
def numpy_version(): #Explicitly Numpy based with vectorization
    Z = X + Y 

We call the developed functions and measure the time it takes to execute them once:

In [ ]:
timer_obj1 = Timer("pure_python_version()", 
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", 
                   "from __main__ import numpy_version")

print("Pure python version:",timer_obj1.timeit(10))
print("Numpy version:",timer_obj2.timeit(10))

Pure python version: 0.0814171159999546
Numpy version: 0.005286493000028258


As we can see, the vectorized sum approach with `Numpy` is much faster than the purely `Python` based approach.

## 2.Creating `Numpy` array from `Python` list

Let's start by creating a `numpy` array from a predefined list with te values 165, 170, 171, 180, 189, and 178:

In [ ]:
heights = [165, 170, 171, 180, 189, 178]
print(type(heights))

heights_np = np.array(heights)
print(type(heights_np))

<class 'list'>
<class 'numpy.ndarray'>


The type of object defined at first is a `list`. After conversion with the `.array()` function, the object is converted into a `ndarray` object. This means that we have created an array of multiple dimensions (`n` dimensions) from a `list`. In this case, the `numpy` array is a **one-dimensional array**.

Now let's see how to create a **two-dimensional array**:

In [ ]:
weights = np.array([[50, 45, 56, 78],[78, 89, 59, 90],[89, 78, 69, 70],[67, 69, 89, 70],[90,89, 80, 84],[89, 59, 90, 78]])
print(weights)

[[50 45 56 78]
 [78 89 59 90]
 [89 78 69 70]
 [67 69 89 70]
 [90 89 80 84]
 [89 59 90 78]]


## 3. Exploring some of the key attributes of `ndarray` objects

Multidimensional arrays have the following important attributes:

- `ndim`: number of dimensions of the array
- `shape`: shape of the array in the format `(number_rows, number_columns)`
- `size`: total number of elements
- `dtypes`: type of data stored in the array
- `strides`: number of bytes that must be moved to store each row and column in memory, in the format `(number_bytes_files, number_bytes_columns)`

Let's see an example:

In [ ]:
print("dimension:", weights.ndim)
print("shape:", weights.shape)
print("size:", weights.size)
print("dtype:", weights.dtype)
print("strides:", weights.strides)

dimension: 2
shape: (6, 4)
size: 24
dtype: int64
strides: (32, 8)


The exemplified arrangement has:

- `ndim` of 2 because it is a two-dimensional array.
- `shape` of (6, 4) as it is made up of 6 rows and 4 columns.
- `size` of 24 since it has 24 elements in total, 6 elements per column or what is the same, 4 elements per row.
- int32 `dtypes` because each element of the array is a 32-bit (4-byte) integer
- `strides` of (16, 4) since 16 bytes (4 integers of 4 bytes in the rows) are needed to store each row in memory and 4 bytes (1 integer per column) to store each column in memory.

## Exercise 1

Convert the two-dimensional `ndarray` `weights` into a three-dimensional object without changing its shape.

In [ ]:
# Answer
new_weights = weights.reshape(6,4,1)
print(new_weights)

[[[50]
  [45]
  [56]
  [78]]

 [[78]
  [89]
  [59]
  [90]]

 [[89]
  [78]
  [69]
  [70]]

 [[67]
  [69]
  [89]
  [70]]

 [[90]
  [89]
  [80]
  [84]]

 [[89]
  [59]
  [90]
  [78]]]


## 4. Exploring some of the key functions defined for `numpy` arrays

In this section we are going to explore some of the most important functions of `numpy` arrays:

1. `zeros(shape=(n,m))`: Allows to create a zero-array with the shape (`n` rows, `m` columns)
2. `arange(start=i, stop=j, step=u)`: creates a one-dimensional array whose first value is `i` inclusive, last value is `j` exclusive, and each value varies  `s` steps from the previous.
3. `linspace(start=i, stop=j, num=n)`: creates a one-dimensional array whose first value is `i` inclusive, last value is `j` inclusive and contains `n` values in total. Each value differs from the previous one with the same magnitude that differs from the next.
4. `full(shape=(n,m), fill_value=f)`: Allows to create an array with the shape (`n` rows,` m` columns), where all positions have the value `f`.

Let's delve into each of them:

### 4.1. np.zeros()

The `zeros(shape=(n,m), dtypes)` function creates a zero-array with the shape (`n` rows, `m` columns) and data types of `dtypes`:

In [ ]:
x = np.zeros(shape=(3,5), dtype ="int32")
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


As you can notice, we have created a two-dimensional array of zeros of three rows and five columns where each element is a 32-bit integer.

### 4.2. np.arange()

The `arange(start=i, stop=j, step=u)` function creates a one-dimensional array whose first value is `i` inclusive, last value is `j` exclusive, and each value varies  `s` steps from the previous:

In [ ]:
x = np.arange(start=100, stop=1000, step=100, dtype="int32")
print(x)

[100 200 300 400 500 600 700 800 900]


This function has allowed us to create a one-dimensional array that starts at 100, ends at 1000 (exclusive) and progresses from 100 to 100, with 32-bit integer values.

### 4.3. np.linspace()

The `linspace(start=i, stop=j, num=n)` function creates a one-dimensional array whose first value is `i` inclusive, last value is `j` inclusive and contains `n` values in total. Each value differs from the previous one with the same magnitude that differs from the next. Consider the following example:

In [ ]:
x_lin = np.linspace(start=10, stop=50, num=30)
print(x_lin)

[10.         11.37931034 12.75862069 14.13793103 15.51724138 16.89655172
 18.27586207 19.65517241 21.03448276 22.4137931  23.79310345 25.17241379
 26.55172414 27.93103448 29.31034483 30.68965517 32.06896552 33.44827586
 34.82758621 36.20689655 37.5862069  38.96551724 40.34482759 41.72413793
 43.10344828 44.48275862 45.86206897 47.24137931 48.62068966 50.        ]


We have created a one-dimensional array that varies linearly from 10 to 50 inclusive, for a total of 30 floating numbers.

### 4.4. np.full()

The `full(shape=(n,m), fill_value=f)` function allows to create an array with the shape (`n` rows,` m` columns), where all positions have the value `f`.

In [ ]:
x_ful = np.full(shape=(5,6), fill_value=3)
print(x_ful)

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


We see that a two-dimensional array of 5 rows and 6 columns has been created, all with a value of 3 at their positions.

## 5. Exploring additional attributes and functions

Let's review three additional functions: `.reshape()`, `.flatten()` and `.ravel()`.

### 5.1. Reshaping the array

Let's reshape the `weights` numpy array. First take a look to the contant and the shape of `weights`:

In [ ]:
weights

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [ ]:
weights.shape

(6, 4)

The reshaping procedure is done using the `.reshape((n1,m1))` function, which receives as input parameters a tuple of two values `n1` and `m1` that is, the new shape of the array to be created from the original array:

In [ ]:
weights = weights.reshape((4,6))
weights

array([[50, 45, 56, 78, 78, 89],
       [59, 90, 89, 78, 69, 70],
       [67, 69, 89, 70, 90, 89],
       [80, 84, 89, 59, 90, 78]])

In [ ]:
weights.shape

(4, 6)

Can you see the difference? We have changed the shape of the `weights` array, from 6 rows and 4 columns, to 4 rows and 6 columns. The way the values are distributed in the new array is from left-to-right then top-to-bottom. 

Let's add a new dimension through reshaping the current `weights` array:

In [ ]:
weights = weights.reshape((2,6,2))
weights

array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [ ]:
weights.shape

(2, 6, 2)

Now, the array is three-dimensionally estructured. Two bi-dimensional (2D) arrays conform the new array, and each of the 2D arrays have two rows and six columns.

### 5.2. Flattening the array

The `.flatten()` function returns a copy of an array collapsed into one dimension, no matter how many dimensions the array has. Consider the `weights` two-dimensional array:

In [ ]:
weights

array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

If we flatten the array, we are re-organizing their elements in a one-dimensional array, as follows:

In [ ]:
weights_flattened = weights.flatten()
weights_flattened

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

### 5.3. Raveling the array

The `.ravel()` function returns a flattened view of an array collapsed into one dimension. It works identically to the `.flatten()` function, although a copy in memory is not achieve, just a flatten view of the final result. 

Consider the `weights` two-dimensional array:

In [ ]:
weights_raveld = weights.ravel()

In [ ]:
weights_raveld

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

Some key differences between flattening and raveling the array are:
- `ravel()` function simply returns a flattened view of Numpy array. If you try to modify this view, you will end up with that same changes in the original array. `flatten()` function returns a flattened copy in memory of the array, so that new changes can be made without affecting the original array.
- `ravel()` does not occupy memory, being faster than `flatten()`, which occupies memory when copying the flattened objects.

## Exercise 2

Create an array of 51 elements starting at 100 and ending at 500, using the two functions `np.linspace()` and `np.arange()`. Arrays must have the same content, with the names `array_lin` and `array_ara`, respectively. Verify that the arrays have the same content with the `np.array_equal()` function.

In [ ]:
# Answer
array_lin = np.linspace(start=100, stop=500,num=51)
#print(array_lin)
array_ara = np.arange(start=100,stop=500,step=8)
#print(array_ara)
np.array_equal(array_lin,array_ara)

False

## 6.Array indexing


To access the content of an array we can use indexing through brackets `[ ]`. When using the brackets, we can access the elements on the list by: 
1. Using a **positive single index** starting from 0
2. Using a **negative single index** starting from -1
3. Using **positive index intervals** using the `start:end:step` notation to specify starting and ending values as well as the step.
4. Using **negative index intervals** using the `start:end:step` notation to specify negative index starting and ending values as well as the step.

Occasionally, we can:
- Get ride of the the `step` value as `sart:end`, so that by default we slice the data with a `step` of 1. 
- Get ride of the `start` value as `:fin:step`, and hence our `start` index will be 0, by default.
- Omit the `end` value as `start::step`, specifying the final position as the `end` index by default. 
- Specify the range as `::step`, and hence the `start` position will be 0 and the end position will be the last one of the array.

Let's see how indexing works using the `weights` and `heights_np` arrays:

In [ ]:
weights

array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [ ]:
weights_or = weights.reshape((6,4))
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [ ]:
heights_np

array([165, 170, 171, 180, 189, 178])

### 6.1 Using a positive single index

When using positive indexing, it is important to consider the first position of the array to be 0:

In [ ]:
print("Accessing single element in 1D array:", heights_np[2])
print("Accessing single element in 2D array:", weights_or[1][3])

Accessing single element in 1D array: 171
Accessing single element in 2D array: 90


In [ ]:
heights_np[7]

IndexError: ignored

**Why are we getting this error message?**

Well guessed! It is because position 7 does not exist in the `heights_np` array, it is totally out of the bounds defined by the array's shape and size. The array has 6 elements, the last element being in position 5.

### 6.2 Using a negative single index starting

When using negative indexing, it is important to consider the last position of the array to be -1:

In [ ]:
print("Accessing single element in 1D array:", heights_np[-4])
print("Accessing single element in 2D array:", weights_or[-5][-1])

Accessing single element in 1D array: 171
Accessing single element in 2D array: 90


In [ ]:
heights_np[-8]

IndexError: ignored

**Why are we getting this error message again?**

Well guessed! It is because position -8 does not exist in the `heights_np` array, it is totally out of the bounds defined by the array's shape and size. The array has 6 elements, the last element being in position -1 and the first element being in position -6.

### 6.3 Using positive index intervals

When using positive interval indexing `start:end:step`, the starting value is inclusive and the ending value is exlusive. Here are somoe examples:

In [ ]:
heights_np[:2] # The default start value is 0

array([165, 170])

In [ ]:
heights_np[2:] # The default end value is the last value of the array

In [ ]:
heights_np[2:3] # The ending value is exlusive

In [ ]:
weights[:2, ::2]

In [ ]:
weights[:3, 3::]

In [ ]:
weights[:3, :3, :1]

### 6.4 Using negative index intervals

When using positive interval indexing `start:end:step`, the negative starting value is inclusive and the negative ending value is exlusive. Here are somoe examples:

In [ ]:
heights_np[:-4] # Equivalent to heights_np[:2]

In [ ]:
heights_np[-4:] # Equivalent to heights_np[2:]

In [ ]:
heights_np[-4:-3] # Equivalent to heights_np[2:3]

In [ ]:
weights[:2, -3::] # Equivalent to weights[:3, 3::]

In [ ]:
weights[:3, :-3, :-1] # Equivalent to weights[:3, :3, :1]

## Exercise 3

Consider the `weights_or` array:

1. Select all the values that are in the even positions in the rows and in the odd positions in the columns. Create a new array named `weights_custom1` with these values.
2. Express the `weights_custom1` array flattened with an in-memory copy. Call the new array `weights_custom2`.
3. Select items in positions 2 to 4 inclusive with negative indexing. Name the output array as `weights_custom3`.

In [ ]:
# Answer #1

In [ ]:
# Answer #2

In [ ]:
# Answer #3

## 7.Manipulating `Numpy` arrays


Arrays can be manipulated using arithmetic, logical, or relational operations in an element-wise way. Let's see how these operations are applied, using our arrays `weights_or`, `heights_np`, and and some other arrays that we will create.

### 7.1. Arithmetic operations

We are going to operate the content of the arrays with the four traditional arithmetic operations, addition, subtraction, product, and division. Let's first define our arrays again:

In [ ]:
weights_or

In [ ]:
heights_2 = np.array([165, 175, 180, 189, 187, 186])
print('heights_np:', heights_np) 
print('heights_2: ', heights_2)

Let's add the content of the two arrays element-wise:

In [ ]:
heights_add = heights_np + heights_2
heights_add

The `np.add()` function allows adding the content of arrays element-wise:

In [ ]:
added = np.add(heights_2, heights_np)
added

## Exercise 4

Since we have seen how to add element-wise elements of one-dimensional arrays:
1. Calculate the subtraction, multiplication and division between the `heights_np` and `heights_2` arrays. Compare the results by using the functions: `np.subtract()`, `np.multiply()`, and `np.divide()`.
2. Calculate the product element-wise of the multiplicative inverses ($1/x$) between the arrays `heights_np` and `heights_2`, using numpy functions. For instante, if an element in `heights_np` $x1=5$ and an element in `heights_2` $y1=4$, then the result should be $z=(1/x1)*(1/y1)=1/20=0.05$.

In [ ]:
# Answer substraction

In [ ]:
# Answer multiplication

In [ ]:
# Answer division

In [ ]:
# Answer multiplicative inverse

### 7.2. Logical operations

Logical operations are mathematical expressions whose result is a Boolean value of 0 (False) or 1 (True). Among the most common logical operations are the disjunction `or`, conjunction `and`, and negation `not`operations, among others. Let's see an example:

In [ ]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [ ]:
np.logical_or(x,y)

In [ ]:
np.logical_and(x,y)

In [ ]:
np.logical_not(x)

### 7.3.Comparison - Relational operators

The comparison operators allow us to compare the values of the content of `numpy` arrays element-wise. Some operators of interest (a) equality operator `np.equal()`, (b) less than operator `np.less()`/`np.less_equal()`, (c) greater than operator `np.greater()`/`np.greater_equal()`, and (d) difference operator `np.not_equal()`. It is important to note that the output will always be Boolean 0 (False) or 1 (True).

Let's see some examples:

In [ ]:
x = np.array([1, 8, 3, 7, 3, 21])
y = np.array([4, 8, 1, 7, 6, 9])

In [ ]:
np.equal(x,y)

In [ ]:
np.not_equal(x,y)

In [ ]:
np.less_equal(x,y)

In [ ]:
np.greater_equal(x,y)

In [ ]:
np.array_equal(x,y) # Comparing the entire content of both arrays

In [ ]:
x = np.array([1, 8, 3, 7, 3, 21])
y = np.array(list((1, 8, 3, 7, 3, 21)))
np.array_equal(x,y) # Comparing the entire content of both arrays

## 8. Broadcasting

`numpy` has the ability of operating arrays of different shapes during arithmetic operations using **broadcasting**, so that arithmetic operations on arrays are done on corresponding elements. The boradcasting operation replicates one of the arrays along the dimensions the other, if there is a mismatch of shapes. Consider the following arrays:

In [ ]:
heights_np = heights_np.reshape((6,1))
heights_np

In [ ]:
weights

We are going to add the elements of both arrays:

In [ ]:
broad_np = heights_np + weights
broad_np

Although the arrays have different dimensions, `numpy` makes a sum for the corresponding elements in common rows and columns, in such a way that the elements of the column vector `heights_np` are added with each column of the two-dimensional vector `weights`.

Let's look at one more example:

In [ ]:
x = np.ones((3,4))
y = np.random.random((5,1,4))

In [ ]:
x

In [ ]:
y

In [ ]:
z = x + y
z

Here each row in array `y` has been paired with rows in array `x`, since they have the same amount of column. The result is an array with triple the rows of array `y` and the same number of columns.

## Exercise 5

Propose an array `y` such that the operation $x + y$ results in the array `z`.
```
x = [[14, 15, 18],
    [62, 90, 98],
    [71, 73, 90],
    [40, 24, 17],
    [11, 81, 14],
    [26, 81, 31]]

z = [[24,  40,  58],
    [72, 115, 138],
    [81,  98, 130],
    [50,  49,  57],
    [21, 106,  54],
    [36, 106,  71]]
```

In [ ]:
# Answer

## 9.Matrix multiplication

Let's delve into the element-wise and dot product multiplication between matrices (two-dimensional arrays). First, we define two matrices:

In [ ]:
A = np.array([[1,1,8],[0,1,9],[9,0,8]])
print("Matrix A:\n", A, '\n')

B = np.array([[2,0,0],[3,4,9],[7,8,9]])
print('MATRIX B:\n', B, '\n')

The product between the two matrices can be executed with the classic arithmetic operator `*`:

In [ ]:
print("Element wise multiplication:\n", A*B, '\n')

The dot product of matrices can be executed with the `@` operator or with the numpy `np.dot()` function:

In [ ]:
print("Matrix product:\n", A@B, '\n') # matrix A = (2 ,3) , matrix B= (3,4), output matrix =( 2,4)
print("Dot product:\n", A.dot(B), '\n')

## 10. Arrays with `random` numbers

A random number is a result of a variable combination specified by a distribution function. When no distribution is specified, it is assumed that the continuous uniform distribution in the interval [0,1) is used. Some functions for generating random numpy numbers are:
- `np.random.random()`: returns random floats in the half-open interval [0.0, 1.0)
- `np.random.randint(low, high)`: returns random integers from low (inclusive) to high (exclusive).
- `np.random.normal()`: returns random samples from a normal (Gaussian) distribution.

Let's see some examples:

In [ ]:
np.random.random((4,3))

In [ ]:
np.random.randint(10, 20, size=(2, 4))

In [ ]:
np.random.normal(size=10)

Ee can also specify a `seed`, so that the sequence of random numbers is repeatable (if you execute the following code several times, you will get the same random results):

In [ ]:
from numpy.random import seed
from numpy.random import rand

# Seed random number generator
seed(42)

# Generate random numbers between 0-1
values = rand(10)
print(values)

## 11. Concatenate, and stack `Numpy` arrays

The **concatenation** `np.concatenate()` is a process of joining several arrays to form one, on the same axis. **Stacking** `np.stack()` is a process of joining arrays on a new axis. Let's dive a little bit more on this concepts with practical examples:

In [ ]:
my_array = np.array([1,2,34,5])
x = np.array([1,4,5,6])
print('x: \t  ', x)
print('my_array: ', my_array)

In [ ]:
print('Append:\n',np.append(my_array,x))
y = np.append(my_array, x)

# Concatentate `my_array` and `x`
print('\nConcatenate:\n',np.concatenate((my_array,x)))

In [ ]:
# Stack arrays vertically (row-wise)
print("Stack row wise:")
print(np.vstack((my_array, x)))

In [ ]:
# Stack arrays horizontally
print("Stack horizantally:")
print(np.hstack((my_array,x)))

print("\nAnother way:")
print(np.r_[my_array,x])

In [ ]:
# Stack arrays column-wise
print("Stack column wise:")
print(np.column_stack(( my_array,x)))

print("\nColumn wise repeat:")
print(np.c_[ my_array,x])

As you have seen, when we concatenate the arrays, we do it on the same axis. When stacking arrays, we do it on a new axis.

## 12. Visualize `Numpy` array

To visualize the content of a numpy array we can make use of the `matplotlib.pyplot` library, which allows us to visualize data and its distributions, among many other functions.

In [ ]:
import matplotlib.pyplot as plt

Let's specify an initial state for the Mersenne Twister number generator, a pseudo-random number generator:

In [ ]:
rng = np.random.RandomState(10)  

Now we generate random values of two normal distributions with different mean and standard deviation, a distribution of mean 0 and another of mean 5, stacking them in a single array horizontally:

In [ ]:
a = np.hstack((rng.normal(size=1000),rng.normal(loc=5, scale=2, size=1000)))
a

Let's visualize the data of the number arrangement of the two distributions, in a histogram with the help of the library `matplotlib.pyplot` to which we have aliased `plt`:

In [ ]:
plt.hist(a, bins='auto')
plt.title("Histogram")
plt.show()

As can be seen, this graph denotes the distribution of the two normal distributions with a mean of 0 and 5.

As an additional example, we are creating a meshgrid `np.meshgrid()` with values generated from an array of `numpy` with initial value of 5, final value of -5 (exclusive) and step of 0.01. We have calculated the value of `z` which corresponds to the general equation of a circle, so that we can generate the graph shown below:

In [ ]:
# Create an array
points = np.arange(-5, 5, 0.01)

# Make a meshgrid
xs, ys = np.meshgrid(points, points)
z = np.sqrt(xs ** 2 + ys ** 2)

# Display the image on the axes
plt.imshow(z, cmap=plt.cm.Reds)

# Draw a color bar
plt.colorbar()

# Show the plot
plt.show()

## 13. Save the numpy ndarray object into a npy file

Finally, one of the most important parts of the entire analysis process, the storage of the results. We can do this with the `np.savetxt()` function:

In [ ]:
import numpy as np
x = np.arange(0.0,5.0,1.0)
np.savetxt('test.txt', x, delimiter=',')

## Conclusions

We have learned the fundamentals of the `numpy` library for scientific computing, which allows us to create multidimensional arrays and operate them using arithmetic, logical, and relational operators. We have also learned how to restructure arrangements in various ways, as well as the basic tools for visualization. 

In the next case study, we will see what is related to the `pandas` library, so we are ready to do data analysis dynamically and efficiently!